# Generated by Django 5.0 on 2024-01-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliotoken',
            old_name='portfolio_token_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='token_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='portfoliotoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfoliotoken',
            name='portfolio',
        ),
    ]
