# Generated by Django 5.0 on 2024-01-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0002_rename_portfolio_token_id_portfoliotoken_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
