# Generated by Django 5.0 on 2024-01-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0003_alter_token_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='current_price',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
