# Generated by Django 5.0 on 2024-01-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0004_alter_token_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='current_price',
            field=models.CharField(max_length=50),
        ),
    ]
